name: Docker Container Monitor

on:
  push:
    branches: [ main ]

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            --build-arg ZIP_PASSWORD=${{ secrets.ZIP_PASSWORD }} \
            -t my-container .

      - name: Start 4 containers
        run: |
          for i in 1 2 3 4; do
            NAME="container-$i"

            docker run -d \
              --name $NAME \
              -p 590$i:5901 \
              -p 22$i:22 \
              my-container

            echo "Container iniciado: $NAME"
          done

      - name: Wait 6 minutes
        run: sleep 360

      - name: Stop containers
        run: |
          for i in 1 2 3 4; do
            NAME="container-$i"
            docker stop $NAME || true
            docker rm $NAME || true
          done

      - name: Cleanup
        if: always()
        run: docker system prune -af